"""Pure, versioned contracts shared by Somnus host, guest, and Kerminal.

The package owns only schemas, endpoint names, versions, and envelopes. It
performs no filesystem, socket, process, secret, host, guest, or operator work
at import time.
"""

from __future__ import annotations

from ._validation import ProtocolValidationError
from .agent import (
    AgentContractError,
    AgentEndpoint,
    AgentHealth,
    CommandResult,
    FileWriteResult,
)
from .control import (
    ERROR_CODE_REGISTRY,
    ERROR_EVIDENCE_REGISTRY,
    ControlRequest,
    ControlResponse,
    DiagnosticReference,
    ErrorCode,
    ErrorCodeSpec,
    ErrorCategory,
    ErrorEnvelope,
    ErrorEvidence,
    ErrorEvidenceKind,
    ErrorEvidenceSpec,
    PublicExitCode,
)
from .events import ControlEvent
from .version import (
    CURRENT_PROTOCOL_VERSION,
    CURRENT_SCHEMA_VERSION,
    MINIMUM_PROTOCOL_VERSION,
    PROTOCOL_VERSION,
    SCHEMA_VERSION,
    ProtocolCapabilities,
    ProtocolNegotiation,
    ProtocolNegotiationError,
    ProtocolVersionError,
    ProtocolVersionRange,
    SchemaVersionError,
    SemanticVersion,
    SUPPORTED_PROTOCOL_RANGE,
    UnsupportedProtocolVersionError,
    ensure_supported_protocol_version,
    negotiate_protocol_version,
    require_schema_version,
)
from .vm import (
    ALLOWED_TRANSITIONS,
    IDEMPOTENT_STATES,
    TRANSITION_REQUIREMENTS,
    ImageProvenance,
    ObservationSource,
    ProcessIdentity,
    RuntimeObservation,
    SnapshotReference,
    StorageReference,
    TransitionCause,
    TransitionEvidence,
    TransitionRecord,
    VMContractError,
    VMDefinition,
    VMMigrationError,
    VMPorts,
    VMRecord,
    VMResourceSpec,
    VMState,
    VMTransitionError,
    migrate_vm_record,
)

__all__ = [
    "AgentContractError",
    "AgentEndpoint",
    "AgentHealth",
    "ALLOWED_TRANSITIONS",
    "CommandResult",
    "ControlEvent",
    "ControlRequest",
    "ControlResponse",
    "CURRENT_PROTOCOL_VERSION",
    "CURRENT_SCHEMA_VERSION",
    "ERROR_CODE_REGISTRY",
    "ERROR_EVIDENCE_REGISTRY",
    "DiagnosticReference",
    "ErrorCode",
    "ErrorCodeSpec",
    "ErrorCategory",
    "ErrorEnvelope",
    "ErrorEvidence",
    "ErrorEvidenceKind",
    "ErrorEvidenceSpec",
    "FileWriteResult",
    "IDEMPOTENT_STATES",
    "ImageProvenance",
    "MINIMUM_PROTOCOL_VERSION",
    "ObservationSource",
    "ProcessIdentity",
    "PROTOCOL_VERSION",
    "ProtocolCapabilities",
    "ProtocolNegotiation",
    "ProtocolNegotiationError",
    "ProtocolValidationError",
    "ProtocolVersionError",
    "ProtocolVersionRange",
    "PublicExitCode",
    "RuntimeObservation",
    "SCHEMA_VERSION",
    "SchemaVersionError",
    "SemanticVersion",
    "SUPPORTED_PROTOCOL_RANGE",
    "SnapshotReference",
    "StorageReference",
    "TRANSITION_REQUIREMENTS",
    "TransitionCause",
    "TransitionEvidence",
    "TransitionRecord",
    "UnsupportedProtocolVersionError",
    "VMContractError",
    "VMDefinition",
    "VMMigrationError",
    "VMPorts",
    "VMRecord",
    "VMResourceSpec",
    "VMState",
    "VMTransitionError",
    "ensure_supported_protocol_version",
    "migrate_vm_record",
    "negotiate_protocol_version",
    "require_schema_version",
]
