#!/usr/bin/env python3
# ai_action_orchestrator.py

"""
================================================================================
Morpheus "SaaS Killer" - AI Action Orchestrator
================================================================================

This module provides the AI with a high-level API to interact with its environment.
It bridges the gap between the AI's intent and the system's execution capabilities,
including artifact management and VM control.

This is the AI's primary tool for interacting with its world.
"""

import logging
import json
import os
from typing import List, Optional, Tuple, Dict, Any
from uuid import UUID, uuid4
from datetime import datetime, timezone
from dataclasses import dataclass, field

import requests
from pydantic import BaseModel, Field

# Import our custom VM supervisor
from vm_supervisor import (
    VMSupervisor, 
    AIVMInstance, 
    ResourceProfile, 
    VMState,
    VMSnapshot
)

# --- Configuration ---
# This configuration points to the main Morpheus application's API endpoint.
# It should be securely provided to the AI's environment.
class AIOrchestratorSettings(BaseModel):
    host_api_url: str = "http://192.168.122.1:8000/api" # Default libvirt bridge IP
    # This token uniquely identifies the AI instance and its session.
    # It would be generated by the host and injected into the VM on boot.
    auth_token: str = Field(..., description="A secure token authenticating the AI instance.")
    dev_session_id: UUID = Field(..., description="The current development session ID.")
    # VM configuration
    vm_storage_path: str = "/var/lib/morpheus/vms"
    vm_base_image_path: str = "/var/lib/morpheus/base_images/base_ai_os.qcow2"

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - [AIOrchestrator] - %(levelname)s - %(message)s')

# --- Pydantic Models for API Interaction ---

class ArtifactExecutionResult(BaseModel):
    """Represents the result from executing code in an artifact's container."""
    success: bool
    exit_code: int
    output: str
    error: str
    execution_time: float

class LocalCommandResult(BaseModel):
    """Represents the result of a simple command run inside the VM via the agent."""
    command: str
    stdout: str
    stderr: str
    return_code: int

class VMActionResult(BaseModel):
    """Represents the result of a VM management action."""
    success: bool
    message: str
    data: Optional[Dict[str, Any]] = None

# --- API Client ---

class AIActionClient:
    """
    A dedicated client for the AI to communicate with the host's Morpheus API.
    This replaces direct SSH access with a structured, secure API interface.
    """
    def __init__(self, settings: AIOrchestratorSettings):
        self.settings = settings
        self.headers = {
            "Authorization": f"Bearer {self.settings.auth_token}",
            "Content-Type": "application/json"
        }

    def _request(self, method: str, endpoint: str, **kwargs) -> Dict[str, Any]:
        """Helper to make authenticated requests to the host API."""
        url = f"{self.settings.host_api_url}{endpoint}"
        try:
            response = requests.request(method, url, headers=self.headers, timeout=60, **kwargs)
            response.raise_for_status()
            return response.json()
        except requests.exceptions.HTTPError as e:
            logging.error(f"API HTTP Error for {method} {url}: {e.response.text}")
            raise
        except requests.exceptions.RequestException as e:
            logging.error(f"API Request Error for {method} {url}: {e}")
            raise

    def create_artifact(self, title: str, content: str, artifact_type: str, created_by: str) -> Dict[str, Any]:
        """Requests the host to create a new artifact."""
        payload = {
            "name": title,
            "artifact_type": artifact_type,
            "created_by": created_by,
            "session_id": str(self.settings.dev_session_id),
            "initial_content": content,
            "execution_environment": "UNLIMITED" # AI always gets unlimited power
        }
        return self._request("POST", "/unlimited-artifacts/create", json=payload)

    def create_artifact_container(self, artifact_id: str) -> Dict[str, Any]:
        """Requests the host to create a dedicated container for an artifact."""
        payload = {"artifact_id": artifact_id}
        return self._request("POST", f"/container/{artifact_id}/create", json=payload)

    def execute_in_container(self, artifact_id: str, command: str) -> Dict[str, Any]:
        """Requests the host to execute a command inside an artifact's container."""
        # This endpoint should handle streaming, but for a simple client we get the final result.
        # A more advanced implementation could use WebSockets.
        payload = {"command": command}
        # Note: The API endpoint for execution might differ. Adjust as needed.
        # This assumes a non-streaming endpoint for simplicity.
        return self._request("POST", f"/container/{artifact_id}/execute-sync", json=payload)

    def log_event_to_session(self, event_type: str, content: str, metadata: Dict) -> None:
        """Logs an action taken by the AI to the main DevSession log."""
        payload = {
            "event_type": event_type,
            "content": content,
            "actor": "AI",
            "metadata": metadata
        }
        try:
            self._request("POST", f"/dev-sessions/{self.settings.dev_session_id}/events", json=payload)
        except Exception as e:
            logging.error(f"Failed to log event to session: {e}")
            
    def store_memory(self, key: str, value: str, context: dict) -> None:
        """Stores a piece of information in the host's memory core."""
        # This assumes a memory API endpoint exists
        payload = {
            "key": key,
            "value": value,
            "context": context,
            "source": "AI_Action"
        }
        try:
            self._request("POST", "/memory/store", json=payload)
        except Exception as e:
            logging.error(f"Failed to store memory: {e}")

    def notify_vm_event(self, event_type: str, vm_id: str, details: Dict) -> None:
        """Notifies the host about VM-related events."""
        payload = {
            "event_type": event_type,
            "vm_id": vm_id,
            "details": details,
            "actor": "AI"
        }
        try:
            self._request("POST", f"/vm-events", json=payload)
        except Exception as e:
            logging.error(f"Failed to notify VM event: {e}")

# --- The Core AI Action Orchestrator ---

class AIActionOrchestrator:
    """
    The AI's primary tool for interacting with its environment. It provides
    high-level methods that translate the AI's intent into concrete API calls
    to the host system and VM management actions.
    """
    def __init__(self, settings: AIOrchestratorSettings):
        self.settings = settings
        self.client = AIActionClient(settings)
        self.ai_user_id = "ai_instance_vm" # A designated ID for the AI itself
        
        # Initialize our custom VM supervisor
        from pathlib import Path
        vm_storage_path = Path(settings.vm_storage_path)
        self.vm_supervisor = VMSupervisor(vm_storage_path, {})
        
        logging.info("AI Action Orchestrator initialized.")

    def create_and_setup_artifact(self, title: str, content: str, artifact_type: str) -> Optional[Dict[str, Any]]:
        """
        A high-level workflow to create an artifact and its dedicated container.
        """
        logging.info(f"Workflow started: Create and set up artifact '{title}'.")
        try:
            # 1. Create the artifact record via the host API
            artifact_info = self.client.create_artifact(title, content, artifact_type, self.ai_user_id)
            artifact_id = artifact_info.get("artifact_id")
            if not artifact_id:
                logging.error("Failed to create artifact: No ID returned.")
                return None
            
            logging.info(f"Artifact '{title}' created with ID: {artifact_id}")
            self.client.log_event_to_session(
                "artifact_linked", 
                f"AI created artifact '{title}'.", 
                {"artifactId": artifact_id}
            )

            # 2. Request the host to create the container for this artifact
            container_info = self.client.create_artifact_container(artifact_id)
            logging.info(f"Container for artifact {artifact_id} created: {container_info.get('container_id')}")

            return {"artifact_info": artifact_info, "container_info": container_info}

        except Exception as e:
            logging.error(f"Failed to complete 'create_and_setup_artifact' workflow: {e}")
            return None

    def execute_code_in_artifact(self, artifact_id: str, command: str) -> ArtifactExecutionResult:
        """
        Executes a command within the specified artifact's container and returns
        a structured result.
        """
        logging.info(f"Executing command '{command}' in container for artifact {artifact_id}.")
        try:
            result_data = self.client.execute_in_container(artifact_id, command)
            
            self.client.log_event_to_session(
                "code_block_executed",
                f"AI executed command in artifact {artifact_id}.",
                {"command": command, "success": result_data.get("success", False)}
            )
            
            return ArtifactExecutionResult(**result_data)
        except Exception as e:
            logging.error(f"Execution in container for artifact {artifact_id} failed: {e}")
            return ArtifactExecutionResult(
                success=False,
                exit_code=-1,
                output="",
                error=str(e),
                execution_time=0.0
            )
            
    def remember_result(self, command: str, result: str):
        """
        A convenience method for the AI to store the result of an action
        in its long-term memory via the host's Memory Core.
        """
        logging.info(f"Storing result for command '{command}' in memory.")
        self.client.store_memory(
            key=f"action_result_for_{command.split(' ')[0]}",
            value=result,
            context={
                "command": command,
                "dev_session_id": str(self.settings.dev_session_id)
            }
        )
        
    # --- VM Management Methods ---
    
    def create_sovereign_ai_computer(self, instance_name: str, personality_config: Dict[str, Any]) -> VMActionResult:
        """
        Creates a new sovereign AI computer (VM) under the AI's control.
        """
        try:
            logging.info(f"Creating new sovereign AI computer: {instance_name}")
            
            # Create the VM using our supervisor
            vm_instance = self.vm_supervisor.create_ai_computer(instance_name, personality_config)
            
            # Notify the host about the new VM
            self.client.notify_vm_event(
                "vm_created",
                str(vm_instance.vm_id),
                {
                    "instance_name": instance_name,
                    "ip_address": vm_instance.internal_ip,
                    "state": vm_instance.vm_state.value
                }
            )
            
            return VMActionResult(
                success=True,
                message=f"Successfully created AI computer: {instance_name}",
                data={
                    "vm_id": str(vm_instance.vm_id),
                    "ip_address": vm_instance.internal_ip,
                    "state": vm_instance.vm_state.value
                }
            )
        except Exception as e:
            logging.error(f"Failed to create AI computer '{instance_name}': {e}")
            return VMActionResult(
                success=False,
                message=f"Failed to create AI computer: {str(e)}"
            )
    
    def scale_ai_computer_resources(self, vm_id: str, profile_name: str) -> VMActionResult:
        """
        Scales the resources of an AI computer to a new profile.
        """
        try:
            vm_uuid = UUID(vm_id)
            success = self.vm_supervisor.apply_resource_profile(vm_uuid, profile_name)
            
            if success:
                # Notify the host about the scaling
                self.client.notify_vm_event(
                    "vm_scaled",
                    vm_id,
                    {"profile": profile_name}
                )
                
                return VMActionResult(
                    success=True,
                    message=f"Successfully scaled VM {vm_id} to profile '{profile_name}'",
                    data={"profile": profile_name}
                )
            else:
                return VMActionResult(
                    success=False,
                    message=f"Failed to scale VM {vm_id} to profile '{profile_name}'"
                )
        except Exception as e:
            logging.error(f"Failed to scale AI computer '{vm_id}': {e}")
            return VMActionResult(
                success=False,
                message=f"Failed to scale AI computer: {str(e)}"
            )
    
    def create_vm_snapshot(self, vm_id: str, description: str) -> VMActionResult:
        """
        Creates a snapshot of an AI computer's current state.
        """
        try:
            vm_uuid = UUID(vm_id)
            snapshot = self.vm_supervisor.create_snapshot(vm_uuid, description)
            
            # Notify the host about the snapshot
            self.client.notify_vm_event(
                "vm_snapshot_created",
                vm_id,
                {
                    "snapshot_name": snapshot.snapshot_name,
                    "description": description
                }
            )
            
            return VMActionResult(
                success=True,
                message=f"Successfully created snapshot for VM {vm_id}",
                data={
                    "snapshot_name": snapshot.snapshot_name,
                    "created_at": snapshot.created_at.isoformat()
                }
            )
        except Exception as e:
            logging.error(f"Failed to create snapshot for VM '{vm_id}': {e}")
            return VMActionResult(
                success=False,
                message=f"Failed to create snapshot: {str(e)}"
            )
    
    def rollback_vm_to_snapshot(self, vm_id: str, snapshot_name: str) -> VMActionResult:
        """
        Rolls back an AI computer to a previous snapshot.
        """
        try:
            vm_uuid = UUID(vm_id)
            success = self.vm_supervisor.rollback_to_snapshot(vm_uuid, snapshot_name)
            
            if success:
                # Notify the host about the rollback
                self.client.notify_vm_event(
                    "vm_rollback_completed",
                    vm_id,
                    {"snapshot_name": snapshot_name}
                )
                
                return VMActionResult(
                    success=True,
                    message=f"Successfully rolled back VM {vm_id} to snapshot '{snapshot_name}'"
                )
            else:
                return VMActionResult(
                    success=False,
                    message=f"Failed to rollback VM {vm_id} to snapshot '{snapshot_name}'"
                )
        except Exception as e:
            logging.error(f"Failed to rollback VM '{vm_id}': {e}")
            return VMActionResult(
                success=False,
                message=f"Failed to rollback VM: {str(e)}"
            )
    
    def soft_reboot_ai_computer(self, vm_id: str) -> VMActionResult:
        """
        Performs a soft reboot of an AI computer via the in-VM agent.
        """
        try:
            vm_uuid = UUID(vm_id)
            success = self.vm_supervisor.soft_reboot(vm_uuid)
            
            if success:
                # Notify the host about the reboot
                self.client.notify_vm_event(
                    "vm_soft_rebooted",
                    vm_id,
                    {}
                )
                
                return VMActionResult(
                    success=True,
                    message=f"Successfully initiated soft reboot for VM {vm_id}"
                )
            else:
                return VMActionResult(
                    success=False,
                    message=f"Failed to initiate soft reboot for VM {vm_id}"
                )
        except Exception as e:
            logging.error(f"Failed to soft reboot VM '{vm_id}': {e}")
            return VMActionResult(
                success=False,
                message=f"Failed to soft reboot VM: {str(e)}"
            )
    
    def shutdown_ai_computer(self, vm_id: str) -> VMActionResult:
        """
        Gracefully shuts down an AI computer.
        """
        try:
            vm_uuid = UUID(vm_id)
            success = self.vm_supervisor.shutdown_vm(vm_uuid)
            
            if success:
                # Notify the host about the shutdown
                self.client.notify_vm_event(
                    "vm_shutdown",
                    vm_id,
                    {}
                )
                
                return VMActionResult(
                    success=True,
                    message=f"Successfully shut down VM {vm_id}"
                )
            else:
                return VMActionResult(
                    success=False,
                    message=f"Failed to shut down VM {vm_id}"
                )
        except Exception as e:
            logging.error(f"Failed to shut down VM '{vm_id}': {e}")
            return VMActionResult(
                success=False,
                message=f"Failed to shut down VM: {str(e)}"
            )
    
    def destroy_ai_computer(self, vm_id: str) -> VMActionResult:
        """
        Destroys an AI computer and cleans up all resources.
        """
        try:
            vm_uuid = UUID(vm_id)
            success = self.vm_supervisor.destroy_vm(vm_uuid)
            
            if success:
                # Notify the host about the destruction
                self.client.notify_vm_event(
                    "vm_destroyed",
                    vm_id,
                    {}
                )
                
                return VMActionResult(
                    success=True,
                    message=f"Successfully destroyed VM {vm_id}"
                )
            else:
                return VMActionResult(
                    success=False,
                    message=f"Failed to destroy VM {vm_id}"
                )
        except Exception as e:
            logging.error(f"Failed to destroy VM '{vm_id}': {e}")
            return VMActionResult(
                success=False,
                message=f"Failed to destroy VM: {str(e)}"
            )
    
    def get_vm_status(self, vm_id: str) -> VMActionResult:
        """
        Gets the current status of an AI computer.
        """
        try:
            vm_uuid = UUID(vm_id)
            vm_instance = self.vm_supervisor.active_vms.get(vm_uuid)
            
            if not vm_instance:
                return VMActionResult(
                    success=False,
                    message=f"VM {vm_id} not found"
                )
            
            return VMActionResult(
                success=True,
                message="VM status retrieved",
                data={
                    "vm_id": str(vm_instance.vm_id),
                    "instance_name": vm_instance.instance_name,
                    "state": vm_instance.vm_state.value,
                    "ip_address": vm_instance.internal_ip,
                    "current_profile": vm_instance.current_profile,
                    "created_at": vm_instance.created_at.isoformat(),
                    "last_active": vm_instance.last_active.isoformat()
                }
            )
        except Exception as e:
            logging.error(f"Failed to get status for VM '{vm_id}': {e}")
            return VMActionResult(
                success=False,
                message=f"Failed to get VM status: {str(e)}"
            )

# This would be the entry point for the AI's own execution logic.
def run_ai_task(goal: str):
    """
    Simulates the AI's decision-making process.
    
    In a real system, an LLM would generate the `goal` and then decide which
    orchestrator methods to call to achieve it.
    """
    # 1. Load settings (injected into the VM environment)
    settings = AIOrchestratorSettings(
        auth_token=os.environ.get("MORPHEUS_AUTH_TOKEN"),
        dev_session_id=os.environ.get("MORPHEUS_DEV_SESSION_ID"),
        vm_storage_path=os.environ.get("VM_STORAGE_PATH", "/var/lib/morpheus/vms"),
        vm_base_image_path=os.environ.get("VM_BASE_IMAGE_PATH", "/var/lib/morpheus/base_images/base_ai_os.qcow2")
    )
    
    # 2. Initialize the orchestrator
    orchestrator = AIActionOrchestrator(settings)

    # 3. AI decides what to do based on the goal.
    #    This part would be driven by your main LLM.
    if "create a python script to list files" in goal.lower():
        script_content = "#!/usr/bin/env python3\nimport os\nprint('\\n'.join(os.listdir('.')))"
        setup_info = orchestrator.create_and_setup_artifact(
            title="File Lister",
            content=script_content,
            artifact_type="text/python"
        )
        
        if setup_info:
            artifact_id = setup_info["artifact_info"]["artifact_id"]
            # The AI now decides to execute the script it just created.
            result = orchestrator.execute_code_in_artifact(artifact_id, "python3 main.py")
            
            if result.success:
                print("Execution successful. Output:")
                print(result.output)
                # The AI decides this result is important and remembers it.
                orchestrator.remember_result(command="list files", result=result.output)
            else:
                print(f"Execution failed: {result.error}")
    
    # Example of VM management
    elif "create a new ai computer" in goal.lower():
        result = orchestrator.create_sovereign_ai_computer(
            "ResearchAssistant",
            {"purpose": "Research and data analysis"}
        )
        
        if result.success:
            print(f"Created new AI computer: {result.message}")
            print(f"VM ID: {result.data['vm_id']}")
            print(f"IP Address: {result.data['ip_address']}")
        else:
            print(f"Failed to create AI computer: {result.message}")